export default [
  'Choose walking freely during quarantine. ',
  'Choose a meme president. ',
  'Choose slut shaming. ',
  'Choose revenge porn. ',
  'Choose Xanax. ',
  'Choose hydroxychloroquine. ',
  'Choose the same fucking password for every fucking online service. ',
  'Choose a 4-hour daily commute. ',
  'Choose neoliberalism. ',
  'Choose dictatorship. ',
  'Choose your feed. ',
  'Choose day trading until your whole family is broke. ',
  'Choose smart devices that spy on you and your body physiology. ',
  'Choose flat Earth. ',
  'Choose toxic masculinity. ',
  'Choose hyper-productivity. ',
  'Choose self-help. ',
  'Choose not giving a f*ck. ',
  'Choose mainstream. ',
  'Choose hype. ',
  "Choose cheap ebooks that won't challenge you. ",
  'Choose YA and chicklit and bland massproduced airport thrillers with sanitised violence. ',
  'Choose being the victim of the Dunning-Kruger effect. ',
  'Choose slave-made clothes. ',
  'Choose trans-exclusionary radical feminism. ',
  'Choose financing an used car. ',
  'Choose denialism. ',
  'Choose whatever you want. ',
  'Choose not being able to retire and old-age homelessness. ',
  'Choose overpriced hardware. ',
  'Choose an infinite jest. ',
  'Choose not testing your software. ',
  'Choose media violence. ',
  'Choose mindless distractions but also mindfulness at work. ',
  'Choose Alexa, Google Home, Siri. ',
  'Choose cameras watching every fucking second of your day. ',
  'Choose wellness apps. ',
  'Choose essential oils. ',
  'Choose vaping. ',
  'Choose Himalayan salt. ',
  'Choose mass shootings. ',
  'Choose this lorem ipsum generator. ',
  'Choose internet challenges. ',
  'Choose good streaming services. ',
  'Choose being fitter, happier. ',
  'Choose your friends. ',
  'Choose entrepreneurship. ',
  'Choose disruption. ',
  'Choose key performance indicators. ',
  'Choose fads. ',
  'Choose trends. ',
  'Choose competition. ',
  'Choose money. ',
  'Choose the red pill. ',
  'Choose zeitgeist and its addendum. ',
  'Choose a playlist. ',
  'Choose yet another lorem ipsum generator. ',
  'Choose a messenger owned by Facebook. ',
  'Choose patriarchy, which consumes your very soul. ',
  "Choose shallow TV series poking at social issues without stepping out of the comfort zone and pretending they're actually no. t shallow",
  'Choose gender before race. ',
  'Choose games with meaningless choices. ',
  'Choose labels. ',
  'Choose gig economy. ',
  'Choose burnout syndrome. ',
  'Choose creative idleness. ',
  'Choose ending social distancing too soon. ',
  'Choose chasing another fad hoping it will fix your life. ',
  'Choose microtransactions. ',
];
